/*INSERE DADOS NA TABELA DE USERS*/
INSERT INTO LABDATABASE.USERS (USER_ID, USER_FULLNAME, CPF, PHONE, USER_EMAIL)
VALUES (USER_ID_SEQ.NEXTVAL, 'Henrique Schraiber', '03612558175', '27995815978', 'henriquetest@gmail.com');
INSERT INTO LABDATABASE.USERS (USER_ID, USER_FULLNAME, CPF, PHONE, USER_EMAIL)
VALUES (USER_ID_SEQ.NEXTVAL, 'Guilherme Kill', '95112558323', '27995815932', 'Guilhermetest@gmail.com');

/*INSERE DADOS NA TABELA DE MOVIE_TYPE*/

INSERT INTO LABDATABASE.MOVIE_TYPE (MOVIE_TYPE_ID, MOVIE_TYPE_NAME)
VALUES (MOVIE_TYPE_ID_SEQ.NEXTVAL, 'Ação');
INSERT INTO LABDATABASE.MOVIE_TYPE (MOVIE_TYPE_ID, MOVIE_TYPE_NAME)
VALUES (MOVIE_TYPE_ID_SEQ.NEXTVAL, 'Terror');

/*INSERE DADOS NA TABELA DE MOVIE*/
INSERT INTO LABDATABASE.MOVIE (MOVIE_ID, MOVIE_TYPE_ID, MOVIE_NAME, MOVIE_DESCRIPTION, MOVIE_PRICE)
VALUES (MOVIE_ID_SEQ.NEXTVAL, 1, 'O pacto', 'O pacto é um filme de ação baseado em...', 30.0);
INSERT INTO LABDATABASE.MOVIE (MOVIE_ID, MOVIE_TYPE_ID, MOVIE_NAME, MOVIE_DESCRIPTION, MOVIE_PRICE)
VALUES (MOVIE_ID_SEQ.NEXTVAL, 2, 'Annabele', 'Annabelle é um filme de terror baseado em ...', 50.0);


INSERT INTO LABDATABASE.USER_MOVIE VALUES(USER_MOVIE_ID_SEQ.NEXTVAL, 1, 1, 30.0);

INSERT INTO LABDATABASE.USER_MOVIE VALUES(USER_MOVIE_ID_SEQ.NEXTVAL, 1, 2, 50.0);

INSERT INTO LABDATABASE.USER_MOVIE VALUES(USER_MOVIE_ID_SEQ.NEXTVAL, 2, 2, 50.0);